export const districts = [
  "Darjeeling",
  "Kolkata",
  "Howrah",
  "North 24 Parganas",
  "South 24 Parganas",
  "Hooghly",
  "Paschim Bardhaman",
  "Purba Bardhaman",
  "Nadia",
  "Murshidabad",
  "Birbhum",
  "Bankura",
  "Purulia",
  "Cooch Behar",
  "Jalpaiguri",
  "Alipurduar",
  "Malda",
  "Uttar Dinajpur",
  "Dakshin Dinajpur",
  "Kalimpong",
  "Jhargram",
];
